MiniLibX 3 "September 19, 2002"
NAME
MiniLibX - Simple X-Window Interface Library for students
SYNOPSYS
#include <mlx.h>

void *mlx_init();

DESCRIPTION
MiniLibXはX-Windowプログラミングの知識を必要としない、グラフィカルなプログラムを作る簡単な方法の一つです。
単純なウィンドウ作成、描写ツール、画像管理、基本的なイベント管理を提供します。

X-WINDOW CONCEPT
X-Windowは、Unix用のネットワーク指向のグラフィカルシステムです。これは、2つの主要な部分に基づいています。
あなたのソフトウェアは、画面に何かを描画したり、キーボードとマウスのエントリを取得したりしたいと考えています。
一方、X-serverは画面、キーボード、マウスを管理します（「ディスプレイ」と呼ばれることもあります）。
描写命令（ソフトウェアからX-serverへ）とキーボード/マウスイベント（X-serverからソフトウェアへ）を送信するために、
これら2つのエンティティ間にネットワーク接続を確立する必要があります。

INCLUDE FILE
MiniLibX APIを正しく利用するために、mlx.hをインクルードするべきです。
これは、関数のプロトタイプ宣言のみを含み、構造体は要求されていません。

LIBRARY FUNCTIONS
まず、あなたのソフトウェアとディスプレイの接続の初期化が必要です。
この接続が確立すると、他のMiniLibX関数を利用して、X-serverへ「黄色のピクセルを描写したい」、
「ユーザーがキーを押した？」などのメッセージを送ることができるようになります。
mlx_init関数は、この接続を作ります。引数は必要なく、返り値としてライブラリを呼び出すためのvoidポインターを返します。

他のMiniLibX関数は下記のマニュアルページで説明します。

mlx_new_window	: ウィンドウ管理
mlx_pixel_put	: ウィンドウ内描写
mlx_new_image	: 画像操作
mlx_loop		: キーボード、マウスイベント管理

LINKING MiniLibX
MiniLibX関数を使うために、あなたのソフトウェアにいくつかのライブラリをリンクする必要があります。
そのためリンク時に下記の引数を追加してください。

-lmlx -lXext -lX11

また、これらのライブラリの関数のpathを-L flagで指定する必要があるかもしれません。

RETURN VALUES
mlx_init()
X-serverとの接続に失敗したとき、NULLをリターンします。
そうでなければ、接続識別子として、NULLでないポインターをリターンします。

.SH SEE ALSO
mlx_new_window(3), mlx_pixel_put(3), mlx_new_image(3), mlx_loop(3)

.SH AUTHOR
Copyright ol@ - 2002-2014 - Olivier Crouzet
