.TH MiniLibX 3 "September 19, 2002"
.SH NAME
MiniLibX - Handle events
.SH SYNOPSYS

int mlx_loop(void *mlx_ptr);
int mlx_key_hook(void *win_ptr, int (*funct_ptr)(), void *param);
int mlx_mouse_hook(void *win_ptr, int (*funct_ptr)(), void *param);
int mlx_expose_hook(void *win_ptr, int (*funct_ptr)(), void *param);
int mlx_loop_hook(void *mlx_ptr, int (*funct_ptr)(), void *param);

X-WINDOW EVENTS
X-Window systemは双方向性を持ちます。
一方ではプログラムがピクセルや画像などをスクリーンに表示する指令を送り、
もう一方ではスクリーン側のキーボードやマウスから情報を得ることができます。
そのために、プログラムは”イベント”をキーボードやマウスから受け取ります。

DESCRIPTION
イベントを受け取るためには、mlx_loop関数をreturnせずに使わなけれいけません。
この無限ループは、イベントを待ち続け、イベントに対応したユーザー定義の関数をコールします。
接続識別子mlx_ptrを引数として必要とします。(mlxマニュアル参照)
以下の三つのイベントに任意の関数を割り当てることができます。
・キー押下
・マウスボタン押下
・ウィンドウ再描画（これは"Expose"イベントと呼ばれ、管理するのはあなたのプログラムの仕事です。）
同じイベントに対して、ウィンドウごとに異なる関数を定義できます。

mlx_key_hook関数、mlx_mouse_hook関数、 mlx_expose_hook関数は同じ様に動作します。
関数ポインタfunct_ptrに、イベントが発生したときコールしたい関数を指定します。
ウィンドウ識別子win_ptrで、イベントを待つウィンドウを指定します。
paramはコールする関数に渡す引数を格納します。

.B mlx_loop_hook関数の構文は、mlx_loop関数と同じですが、与えられたはイベントが発生しなかったときにコールされます。

イベントをキャッチしたとき、
When it catches an event, the MiniLibX calls the corresponding function
with fixed parameters:
.nf

  expose_hook(void *param);
  key_hook(int keycode,void *param);
  mouse_hook(int button,int x,int y,void *param);
  loop_hook(void *param);

.fi
These function names are arbitrary. They here are used to distinguish
parameters according to the event. These functions are NOT part of the
MiniLibX.

.I param
is the address specified in the mlx_*_hook calls. This address is never
used nor modified by the MiniLibX. On key and mouse events, additional
information is passed:
.I keycode
tells you which key is pressed (look for the X11 include file "keysymdef.h"),
(
.I x
,
.I y
) are the coordinates of the mouse click in the window, and
.I button
tells you which mouse button was pressed.

.SH GOING FURTHER WITH EVENTS
The MiniLibX provides a much generic access to all X-Window events. The
.I mlx.h
include define
.B mlx_hook()
in the same manner mlx_*_hook functions work. The event and mask values
will be taken from the X11 include file "X.h".

See source code of mlx_int_param_event.c to find out how the MiniLibX will
call your own function for a specific event.

.SH SEE ALSO
mlx(3), mlx_new_window(3), mlx_pixel_put(3), mlx_new_image(3)

.SH AUTHOR
Copyright ol@ - 2002-2014 - Olivier Crouzet
